version: '3.8'

services:
  db:
    image: mariadb:10.4.28
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./NGO_Management.sql:/docker-entrypoint-initdb.d/NGO_Management.sql
    networks:
      - app-network

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: NGO_Management
      DB_USER: root
    networks:
      - app-network

networks:
  app-network:

volumes:
  db_data:
