import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Navbar Component */}
        <nav className="flex justify-between items-center bg-gray-800 p-6">
          <div className="text-white text-3xl font-bold mx-auto">
            NGO MANAGEMENT SYSTEMS
          </div>
          <div className="space-x-4">
            <button className="text-white px-4 py-2 border border-gray-500 rounded hover:bg-gray-700">
              Sign In
            </button>
            <button className="text-white px-4 py-2 border border-gray-500 rounded hover:bg-gray-700">
              Register
            </button>
          </div>
        </nav>

        {/* Render children (your page content) */}
        {children}
      </body>
    </html>
  );
}
